postgresql:
 image: orchardup/postgresql
 volumes_from:
  - data
 container_name: pg-container
        
apache-php:
 build: ./docker/php
 ports:
  - "8765:80"
 volumes:
  - .:/var/www/html
  - ./php:/usr/local/etc/php
 links:
  - postgresql:pg
 container_name: web-container
        
data:
 image: centos:centos7
 command: /bin/bash
 volumes:
 - /var/lib/postgresql
 container_name: data-container
