postgresql:
    image: orchardup/postgresql
    environment:
        - POSTGRES_USER=user
        - POSTGRES_PASSWORD=password
    volumes_from:
        - data
        
apache-php:
    image: php:5.6.19-apache
    ports:
        - "80:80"
    volumes:
        - .:/var/www/html
    links:
        - postgresql:pg
        
phpmyadmin:
    image: phpmyadmin/phpmyadmin:4.5.3.1-1
    ports:
        - "8080:8080"
    links:
        - postgresql:pg
        
data:
  image: centos:centos7
  command: /bin/bash
  volumes:
    - /var/lib/postgresql